Bug-295 - tests for gtest/gmock env
Open-Transactions/opentxs pull request #1768
Opened 2022-02-21 08:41 UTC by spamaa

These are tests, that checks does gtest/gmock basic features works. When we will use a new kind of gmock/gtest feature, we should add a test that verifies if it works at all enviroments.

2022-02-21 16:26 UTC, justusranvier requested changes
See [this comment](https://github.com/Open-Transactions/opentxs-cmake/pull/1#issuecomment-1047025184) for alternatives to universally disabling Weffc++ in all our projects.

The best approach is to use the #pragma GCC technique since modifying the compiler flags for a specific file makes unity builds less effective but if that is too unwieldy turning off Weffc++ on the specific test files that use gmock is also acceptable.

2022-02-21 16:26 UTC, justusranvier commented on tests/dummy/Interfaces/DummyInterface.hpp
> +#if !defined (__TEST_DUMMY_INTERFACES_DUMMYINTERFACE_HPP_INCLUDED__)
Use #pragma once instead of header guards

2022-02-21 16:26 UTC, justusranvier commented on src/CMakeLists.txt
> +    # TEST_END
What are these comments placeholders for?

2022-02-24 07:24 UTC, spamaa commented on tests/dummy/Interfaces/DummyInterface.hpp
> +#if !defined (__TEST_DUMMY_INTERFACES_DUMMYINTERFACE_HPP_INCLUDED__)
#pragma once  works only at compilers that support it, and usually ignored by compilers that do not support it. If it is not supported, compilers usually will not give even warning. At the other hand, define is more error prone. You can mismatch defines, but it almost always produces easy to detect compilation errors. Hence I prefer the define guards. Code is more robust and cost almost nothing. I will change it to keep consistent with remaining code.

2022-02-24 07:24 UTC, spamaa commented on src/CMakeLists.txt
> +    # TEST_END
Sorry, I was using some debug code and it was just for clear identification what is a debug code and what isn't. I have forgot to delete it.

2022-03-03 15:11 UTC, spamaa commented on src/CMakeLists.txt
> +    # TEST_END
done

2022-03-17 14:35 UTC, merged